### ISSUE TITLE
Allow buf lint action to show warnings but still pass

### ISSUE THREAD

**Issue by commure-stabai** [bufbuild/buf-lint-action#11]
The `bufbuild/buf-lint-action@v1` action currently causes the job that calls it to fail if there are any lint problems. Since these lint problems may not be mandatory fixes (especially if they're preexisting problems), it would be nice if the action had an input that causes it not to fail.

It is treated as a failure because the linter is very reasonably returning a nonzero exit code, which GitHub [interprets](https://docs.github.com/en/actions/creating-actions/setting-exit-codes-for-actions) as a failure, so this status would need to be caught. There is also the question of whether the `::warning` signal should be used instead of `::error` in this case, but that doesn't appear to govern any GitHub workflow functionality.

**Comment by lrewega** [comment]
> Since these lint problems may not be mandatory fixes (especially if they're preexisting problems),

You may find configuring `buf lint` to ignore preexisting problems to be a better solution than ignoring the exit status. You can generate the necessary configuration by running [`buf lint --error-format=config-ignore-yaml`](https://docs.buf.build/lint/usage#:~:text=ignore%20all%20existing%20lint%20errors). For example, if you don't yet have a `buf.yaml` you can run `buf lint --error-format=config-ignore-yaml | tee buf.yaml` and then further customize the used or ignored lint rules as you see fit.

> it would be nice if the action had an input that causes it not to fail.

If ignoring existing lint problems doesn't work for you, there are a number of ways to customize how the failure is handled within the workflow for a job or step, such as:

- Set [`job.<job_id>.continue-on-error`](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error) or [`job.<job_id>.steps[*].continue-on-error`](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error) within the job or step respectively. For example, to allow `buf-lint` job to succeed if the `bufbuild/buf-lint-action@v1` step from fails:

  ```diff
    jobs:
      buf-lint:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: bufbuild/buf-setup-action@v0.5.0
          - uses: bufbuild/buf-lint-action@v1
  +         continue_on_error: true
  ```
- Use [`job.<job_id>.if`](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idif) or [`job.<job_id>.steps[*].if`](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsif) to ignore the previous job or step failure. For example, to run the following step regardless:

  ```diff
    jobs:
      lint:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: bufbuild/buf-setup-action@v0.5.0
          - uses: bufbuild/buf-lint-action@v1
          - name: more linting
  +         if: always() 
            run: make lint   
  ```
  though `!cancelled()` might be better than `always()` if you want to respect workflow cancellation.
  
I hope this helps! If not, please let us know by reopening this issue.
