### ISSUE TITLE
Output errors from action

### ISSUE THREAD

**Issue by petelah** [bufbuild/buf-lint-action#110]
It would be good to capture the output from errors in a variable so it can be used to annotate PR's or workflow runs.

**Comment by nicksnyder** [comment]
Thanks for the suggestion. We are going to be doing some work on the actions soon and I have captured this idea in the plan.

**Comment by emcfarlane** [comment]
Hi @petelah, we have been working on a new action [`buf-action`](https://github.com/bufbuild/buf-action) to address many of these issues. Could you clarify the use case for output of errors and raise an issue on `buf-action` if it doesn't solve your case? Closing for now, as the new action always outputs annotations on the PR.
