### ISSUE TITLE
Create release to update dependencies

### ISSUE THREAD

**Issue by adlerhurst** [bufbuild/buf-lint-action#111]
We are using this action and get a deprecation warning of node 16. If I'm right the only step missing is the release as main already is updated to node 20. Could you please consider creating a new release, Thanks.

**Comment by smallsamantha** [comment]
Hi @adlerhurst - [v1.1.1](https://github.com/bufbuild/buf-lint-action/releases/tag/v1.1.1) is now available, appreciate your patience!
