### ISSUE TITLE
buf-lint-action faills if branch is not main. 

### ISSUE THREAD

**Issue by andrewtsun25** [bufbuild/buf-lint-action#15]
When trying to use the `buf-lint-action` on this repo: https://github.com/andrewtsun25/djin-proto/tree/buf-github-actions, the build consistently fails on `buf-lint-action` complaining that "branch is not main". It seems like `buf-setup-action` has completed but this action cares what the branch name is? I've looked through the source code, and there doesn't seem to be a statement that produces this message in any of the `src` files.  I've also read this wiki as well and followed it, except changed all references of "main" to "master": https://docs.buf.build/ci-cd/github-actions. 

Am I missing a step or some undocumented parameter? Or is there a bug in this action?

**Comment by WillAbides** [comment]
The error message you are seeing is related to our transition away from using branches on Buf Schema Registry, not the naming of your git branches.

The workflow file in the repository you linked is using an old version of buf-setup-action which installs an old, pre-release version of `buf`. The older pre-releases don't work well with the `buf.lock` files generated by newer versions of `buf`.

To fix this, you can update your workflow to use `bufbuild/buf-setup-action@v1.3.0` to install  `buf` v1.3.0 or use `bufbuild/buf-setup-action@v1` to always install the latest version of `buf`.

**Comment by andrewtsun25** [comment]
Sounds good, I'll use `bufbuild/buf-setup-action@v1` in my project!
