### ISSUE TITLE
Missing major version tags to support action use

### ISSUE THREAD

**Issue by stevenh** [bufbuild/buf-lint-action#91]
It's idiomatic to create major version tags so users can use them in their actions reducing code churn to get the latest compatible version e.g.
`bufbuild/buf-lint-action@v1`

Could you add the creation of:
* `v<major>`

You can see this in practice [actions/checkout](https://github.com/actions/checkout/tags).

**Comment by emcfarlane** [comment]
@stevenh please take a look at the new [`buf-action`](https://github.com/bufbuild/buf-action) which does support major version tags.
